import { lazy, Suspense, useEffect, useRef, useState } from 'react';
import { ArrowRight, ArrowLeft, Upload, Plus, Layers3, FileImage, Check, X, ChevronDown, ZoomIn, ZoomOut, RotateCcw, AlertCircle, LoaderCircle, ExternalLink } from 'lucide-react';
import Results from './Results';
import ReviewImage from './ReviewImage';
import { useRun } from './useRun';
import { defaultCriteria, type Criterion } from './criteria';

const ModelAccuracy = lazy(() => import('./ModelAccuracy'));
type Screen = 'new'|'progress'|'review'|'results'|'accuracy';
const read = <T,>(key:string, fallback:T):T => {try {return JSON.parse(sessionStorage.getItem(key)||'null') ?? fallback;}catch{return fallback;}};
function screenFromUrl():Screen { const s=location.hash.split('?')[0].replace('#/','');return ['progress','review','results','accuracy'].includes(s)?s as Screen:'new'; }
export default function App(){
 const [screen,setScreen]=useState<Screen>(screenFromUrl);
 const [data,setData]=useState<any>(null);
 const [criteria,setCriteria]=useState<Criterion[]>(()=>read('cottrell.criteria.v2',defaultCriteria));
 const [review,setReview]=useState<any>(()=>read('cottrell.review',{}));
 const [error,setError]=useState('');
 const [stage,setStage]=useState('Opening saved evaluation');
 const [dataset,setDataset]=useState<'test'|'heldout'|'validation'>(()=>read('cottrell.dataset','test'));
 const [source,setSource]=useState<'saved'|'upload'>(()=>new URLSearchParams(location.search).has('run')?'upload':'saved');
 const [capabilities,setCapabilities]=useState<any>(null);
 const [uploads,setUploads]=useState<File[]>([]);
 const [uploadInfo,setUploadInfo]=useState<any>(null);
 const [loading,setLoading]=useState(false);
 const [previewField,setPreviewField]=useState(0);
 const [tag,setTag]=useState(review.tag||'');
 const [note,setNote]=useState(review.note||'');
 const [roi,setRoi]=useState<any>(null);
 const [metadata,setMetadata]=useState(()=>read('cottrell.metadata',{chemistry:'Silicon–graphite (reported)',history:'Fresh from manufacturing',lot:'',supplier:'',reviewer:''}));
 const [savedError,setSavedError]=useState('');
 const [finalizing,setFinalizing]=useState(false);
 const [previewError,setPreviewError]=useState(false);
 const [artifactError,setArtifactError]=useState(false);
 const input=useRef<HTMLInputElement>(null);
 const requestId=useRef(0);
 const engine=useRun((d)=>{setData(d);setPreviewField(0);},()=>go('review'));
 const field=data?.fields?.[previewField];
 const channel=field?.channels?.find((x:any)=>x.name==='BSE')||field?.channels?.[0];
 const imageUrl=channel?.available === false ? undefined : channel?.previewUrl;
 const savedOverlayUrl=(!imageUrl||previewError)?(field?.mask?.overlayUrl||field?.mask?.maskUrl):undefined;
 const replayArtifact=field?.mask?.provenance?.kind==='exploratory replay artifact';
 useEffect(()=>{setPreviewError(false);setArtifactError(false);},[field?.id,imageUrl]);
 useEffect(()=>{const change=()=>setScreen(screenFromUrl());window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
 useEffect(()=>{fetch('/api/capabilities').then(r=>r.json()).then(setCapabilities).catch(()=>{});},[]);
 useEffect(()=>{if(new URLSearchParams(location.search).has('run'))return;let cancelled=false;let timer:ReturnType<typeof setTimeout>;let attempt=0;const fetchData=()=>fetch(`/api/results?dataset=${dataset}`).then(async r=>{if(!r.ok)throw Error('Saved results could not be opened. Reload to retry.');return r.json();}).then(d=>{if(!cancelled){setData(d);setSavedError('');}}).catch(e=>{if(!cancelled){setSavedError(e.message);if(++attempt<4)timer=setTimeout(fetchData,1200);}});fetchData();return()=>{cancelled=true;clearTimeout(timer);};},[dataset]);
 useEffect(()=>{sessionStorage.setItem('cottrell.dataset',JSON.stringify(dataset));setPreviewField(0);},[dataset]);
 useEffect(()=>{sessionStorage.setItem('cottrell.criteria.v2',JSON.stringify(criteria));},[criteria]);
 useEffect(()=>{sessionStorage.setItem('cottrell.metadata',JSON.stringify(metadata));},[metadata]);
 function go(s:Screen){location.hash='/'+s;setScreen(s);setError('');window.scrollTo(0,0);}
 async function loadSaved(){
  engine.clear();setSource('saved');const id=++requestId.current;setStage('Opening saved model output');go('progress');
  try{const r=await fetch(`/api/results?dataset=${dataset}`);if(!r.ok)throw Error('Could not open the saved evaluation. Please try again.');const d=await r.json();if(id!==requestId.current)return;setData(d);setStage('Preparing your review');setReview({});setTag('');setNote('');setRoi(null);sessionStorage.removeItem('cottrell.review');go('review');}
  catch(e){if(id===requestId.current){setError((e as Error).message);}}
 }
 async function validateUploads(files:File[]){
  setUploads(files);setUploadInfo(null);setError('');if(!files.length)return;
  if(files.length>100||files.some(f=>f.size>128*1024*1024)||files.reduce((n,f)=>n+f.size,0)>2*1024**3){setError('Use up to 100 TIFF files, 128 MB each, and 2 GB in total.');return;}
  setLoading(true);const body=new FormData();files.forEach(f=>body.append('files',f));
  try{const r=await fetch('/api/uploads',{method:'POST',body});const j=await r.json();if(!r.ok)throw Error(typeof j.detail==='string'?j.detail:'These files could not be checked.');setUploadInfo(j);}
  catch(e){setError((e as Error).message);}finally{setLoading(false);}
 }
 async function startAnalysis(){
  if(!uploadInfo?.uploadId)return;
  setError('');setStage('Checking files');
  try{await engine.start(uploadInfo.uploadId,criteria,metadata);setData(null);setReview({});setTag('');setNote('');setRoi(null);sessionStorage.removeItem('cottrell.review');go('progress');}
  catch(e){setError((e as Error).message);}
 }
 async function saveReview(skipped=false){
  if(!skipped&&!tag){setError('Choose a tag, or continue without a region review.');return;}
  if(!skipped&&!roi){setError('Draw a region on the image first, or continue without a region review.');return;}
  const r:any={runId:engine.id,taskVersion:'phase-label.v1',fieldId:field?.id,tag:skipped?'Not reviewed':tag,note,roi:skipped?null:{x:roi.x,y:roi.y,width:roi.width,height:roi.height},skipped,reviewer:metadata.reviewer||'Local reviewer',timestamp:new Date().toISOString(),detector:channel?.name,sourceHash:channel?.sha256,regionEvidence:skipped?undefined:roi?.evidence,taskType:'phase_label'};
  setFinalizing(true);setReview(r);sessionStorage.setItem('cottrell.review',JSON.stringify(r));setStage('Saving your review');go('progress');
  try{const res=await fetch('/api/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(r)});if(!res.ok){const problem=await res.json();throw Error(typeof problem.detail==='string'?problem.detail:'The review could not be saved.');}r.persistence='server';}
  catch(e){r.persistence='browser session only';setReview({...r});setFinalizing(false);go('review');setError((e as Error).message);return;}setReview({...r});sessionStorage.setItem('cottrell.review',JSON.stringify(r));
  setStage('Preparing your report');setFinalizing(false);go('results');
 }
 function updateCriterion(id:string,changes:Partial<Criterion>){setCriteria(old=>old.map(c=>c.id===id?{...c,...changes}:c));}
 const selectable=criteria.filter(c=>c.id!=='F12');
 const invalid=criteria.some(c=>c.enabled&&(!Number.isFinite(c.min)||!Number.isFinite(c.max)||c.min>c.max||c.min<c.domain[0]||(['F01','F02','F07','F10','F11'].includes(c.id)&&c.max>c.domain[1])));
 return <div className="app-shell">
  <a className="skip-link" href="#main">Skip to content</a>
  <header className="app-header"><button className="brand" onClick={()=>go('new')} aria-label="Cottrell home"><img className="brand-mark" src="/cottrell-logo.png" alt=""/><span>cottrell<span className="brand-dot">.</span></span></button><nav aria-label="Workspace"><button className={screen==='new'?'nav-link active':'nav-link'} onClick={()=>go('new')}>Inspection workspace</button><button className={screen==='results'?'nav-link active':'nav-link'} disabled={!data||engine.busy} onClick={()=>go('results')}>{engine.id?'Current results':'Saved evaluation'} <span className="count">{data?.fields?.length||'—'}</span></button><button className={screen==='accuracy'?'nav-link active':'nav-link'} onClick={()=>go('accuracy')}>Model Accuracy</button></nav><div className="workspace-meta"><span className="status-dot"/> Local workspace<span className="avatar">C</span></div></header>
  {!['results','accuracy'].includes(screen)&&<div className="workflow" aria-label="Inspection steps">{['Set up','Process','Review','Results'].map((s,i)=>{let at=['new','progress','review','results'].indexOf(screen);return <div key={s} className={i===at?'workflow-step current':i<at?'workflow-step done':'workflow-step'}><span>{i<at?<Check size={12}/>:i+1}</span>{s}{i<3&&<span className="step-line"/>}</div>})}<span className="workflow-context">{source==='saved'?`${data?.mode||'Saved model output'} · ${field?.raw?.pipeline?.git_tag||field?.raw?.pipeline?.git_sha||'recorded run'}`:'New image inspection'}</span></div>}
  <main id="main">
  {screen==='new'&&<>
   <div className="page-heading"><div><h1>A closer look.<br/><span>A clearer next step.</span></h1><p>Inspect your electrode images. Understand the evidence.<br className="desktop-break"/> Know what to investigate next.</p></div><div className="heading-aside"><span className="small-label">MATERIAL INSPECTION</span><span>Image-level screening</span><span className="muted">Reference: Batch 3</span></div></div>
   <div className="setup-grid"><section className="input-column" aria-label="Images and material context">
    <div className="section-title"><h2>Your material</h2><span className="muted">01 / Input</span></div>
    <div className="segmented"><button className={source==='saved'?'selected':''} onClick={()=>{setSource('saved');setError('');}}>Saved evaluation</button><button className={source==='upload'?'selected':''} onClick={()=>{setSource('upload');setError('');}}>Upload images</button></div>
    {source==='saved'?<>
     <div className="dataset-picker" role="radiogroup" aria-label="Saved output to open">{([['test','Test set','6 never-seen images · frozen v1'],['heldout','Official held-out','3 images · scored 2/3, 5/6'],['validation','Training validation','leave-one-image-out']] as const).map(([id,label,hint])=><button key={id} role="radio" aria-checked={dataset===id} className={dataset===id?'dataset-option selected':'dataset-option'} onClick={()=>setDataset(id)}><span>{label}</span><small>{hint}</small>{dataset===id&&<Check size={14}/>}</button>)}</div>
     <div className="sample-view"><div className="sample-toolbar"><span><FileImage size={15}/> {field?`img_${field.id}_BSE.tif`:'Opening image…'}</span><span className="badge">BSE</span></div>{imageUrl&&!previewError?<img src={imageUrl} alt={`Backscattered-electron microscope image of field ${field.id}`} onError={()=>setPreviewError(true)}/>:savedOverlayUrl&&!artifactError?<img src={savedOverlayUrl} alt={`Saved segmentation overlay for field ${field.id}`} onError={()=>setArtifactError(true)}/>:<div className="image-unavailable"><Layers3 size={50}/><p>{savedError||(field?'The original TIFF and saved segmentation artifact are unavailable on this machine':'Preparing microscope preview')}</p></div>}<div className="sample-caption"><span>{savedOverlayUrl&&!artifactError?`${replayArtifact?'Exploratory replay overlay':'Saved segmentation overlay'} · Original TIFF unavailable`:'Fresh manufacturing electrode'}</span><span>{imageUrl&&!previewError?'Original micrograph':savedOverlayUrl&&!artifactError?'Saved run artifact':'Preview unavailable'}</span></div></div>
     {replayArtifact&&<p className="inline-note">Overlay from the later exploratory replay in results/v1_1. All recorded source files match this official image. Official predictions and measurements are unchanged.</p>}
     <div className="field-picker">{data?.fields?.map((f:any,i:number)=><button key={f.id} className={previewField===i?'field-option selected':'field-option'} onClick={()=>setPreviewField(i)}><span className="sample-number">{String(i+1).padStart(2,'0')}</span><span>{f.id}<small>{f.channels?.length||0} detector files</small></span>{previewField===i&&<Check size={15}/>}</button>)}</div>
     <p className="inline-note"><Check size={15}/> Real saved model output. Opening this report does not run the model again.</p>
    </>:<>
      <button className="upload-drop" onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void validateUploads(Array.from(e.dataTransfer.files));}}><Upload size={32}/><h3>Drop your microscope images here</h3><p>or choose files from your computer</p><span className="badge">TIFF · BSE required · up to 128 MB per file</span></button><input ref={input} hidden type="file" accept=".tif,.tiff" multiple onChange={e=>void validateUploads(Array.from(e.target.files||[]))}/>
      {uploads.length>0&&<div className="upload-list">{uploads.map((f,i)=><div key={i}><FileImage size={16}/><span>{f.name}</span><small>{(f.size/1024**2).toFixed(1)} MB</small></div>)}</div>}
      {loading&&<p className="inline-note" role="status"><LoaderCircle className="spin" size={15}/> Checking TIFF headers and image dimensions…</p>}
      {uploadInfo&&<div className="notice"><AlertCircle size={18}/><div><strong>Files checked</strong><p>{uploadInfo.message||uploadInfo.reason||'Files validated. Ready for analysis.'}</p>{uploadInfo.errors?.map((e:any,i:number)=><p key={i}>{typeof e==='string'?e:e.message||JSON.stringify(e)}</p>)}</div></div>}
      {capabilities?.liveRunReady?<div className="notice ready-notice"><Check size={18}/><div><strong>Engine connected</strong><p>Run the fixed measurement recipe on your original images. New results are labelled exploratory.</p></div></div>:<div className="notice"><AlertCircle size={18}/><div><strong>Checking engine availability</strong><p>{capabilities?.reason||'Waiting for the local analysis service.'}</p></div></div>}
    </>}
    <details className="context-details"><summary>Material & review context <ChevronDown size={16}/></summary><div className="metadata-grid"><label>Reported chemistry<input value={metadata.chemistry} onChange={e=>setMetadata({...metadata,chemistry:e.target.value})}/></label><label>Material history<input value={metadata.history} onChange={e=>setMetadata({...metadata,history:e.target.value})}/></label><label>Lot ID<input value={metadata.lot} placeholder="Unknown" onChange={e=>setMetadata({...metadata,lot:e.target.value})}/></label><label>Supplier<input value={metadata.supplier} placeholder="Record not supplied" onChange={e=>setMetadata({...metadata,supplier:e.target.value})}/></label><label>Reviewer<input value={metadata.reviewer} placeholder="Your name" onChange={e=>setMetadata({...metadata,reviewer:e.target.value})}/></label><div className="metadata-note">State of charge: Unknown<br/>Measurements stay in native pixels.</div></div></details>
   </section>
   <section className="criteria-column" aria-label="Screening criteria"><div className="section-title"><h2>Your screening criteria</h2><span className="muted">02 / Limits</span></div><p className="section-intro">Choose what matters for this inspection. These limits change the report, not the model.</p><div className="criteria-summary"><span>{criteria.filter(c=>c.enabled).length} of 11 checks selected</span><div className="criteria-summary-actions"><label className="select-all"><input type="checkbox" aria-label="Select all screening criteria" checked={selectable.length>0&&selectable.every(c=>c.enabled)} ref={el=>{if(el)el.indeterminate=selectable.some(c=>c.enabled)&&!selectable.every(c=>c.enabled);}} onChange={e=>setCriteria(criteria.map(c=>c.id==='F12'?c:{...c,enabled:e.target.checked}))}/>Select all</label><button className="text-button" onClick={()=>setCriteria(defaultCriteria.map(c=>({...c})))}>Reset</button></div></div><div className="criteria-list">{criteria.map(c=><div key={c.id} className={'criterion '+(c.enabled?'enabled ':'')+(c.id==='F12'?'unavailable':'')}><label className="criterion-heading"><input type="checkbox" checked={c.enabled} disabled={c.id==='F12'} onChange={e=>updateCriterion(c.id,{enabled:e.target.checked})}/><span>{c.label}<small>{c.help}</small></span><span className="feature-id">{c.id}</span></label>{c.enabled&&<div className="criterion-controls"><div className="bounds"><label>Minimum<input aria-label={`${c.label} minimum`} type="number" value={Number.isFinite(c.min)?c.min:''} step="any" onChange={e=>updateCriterion(c.id,{min:e.target.value===''?NaN:Number(e.target.value)})}/></label><span>to</span><label>Maximum<input aria-label={`${c.label} maximum`} type="number" value={Number.isFinite(c.max)?c.max:''} step="any" onChange={e=>updateCriterion(c.id,{max:e.target.value===''?NaN:Number(e.target.value)})}/></label><span className="unit">{c.unit}</span></div><input aria-label={`${c.label} upper limit`} type="range" min={c.domain[0]} max={Math.max(c.domain[1],Number.isFinite(c.max)?c.max:0)} step={c.step} value={Number.isFinite(c.max)?c.max:0} onChange={e=>updateCriterion(c.id,{max:Number(e.target.value)})}/><small className="muted">Starting envelope · not a manufacturing standard</small>{(c.min>c.max||c.min<c.domain[0]||(['F01','F02','F07','F10','F11'].includes(c.id)&&c.max>c.domain[1]))&&<p className="error-text">Enter ordered bounds within the measurement’s valid range.</p>}</div>}</div>)}</div></section></div>
   {error&&<p className="error-banner" role="alert">{error}</p>}
   <div className="action-bar"><div><strong>{source==='saved'?`${data?.fields?.length||3} image fields ready to explore`:`${uploads.length} files selected`}</strong><span>{criteria.some(c=>c.enabled)?`${criteria.filter(c=>c.enabled).length} screening criteria selected`:'No criteria selected. Measurements will still be shown.'}</span></div><button className="primary" disabled={invalid||loading||engine.submitting||(source==='saved'?!data:!uploadInfo?.uploadId||!capabilities?.liveRunReady)} onClick={source==='saved'?loadSaved:startAnalysis}>{source==='saved'?'Review saved evaluation':engine.submitting?'Starting analysis…':'Analyse images'} <ArrowRight size={18}/></button></div>
  </>}
  {screen==='progress'&&<div className="processing-layout"><div className="process-image">{imageUrl&&!previewError&&(!engine.id||data?.run?.id===engine.id)?<img src={imageUrl} alt="Selected microscope field" onError={()=>setPreviewError(true)}/>:savedOverlayUrl&&!engine.id?<img src={savedOverlayUrl} alt="Saved segmentation overlay; original TIFF unavailable" onError={()=>setPreviewError(true)}/>:<div className="processing-file"><FileImage size={48}/><strong>{uploads[0]?.name||'Your uploaded microscope images'}</strong><span>Original pixels · fixed model recipe</span></div>}<div className="scan-rule"/></div><div className="process-copy"><span className="badge">{engine.id?'Exploratory analysis':'Saved evaluation'}</span><h1>{engine.run?.state==='failed'?'Cannot analyse these images.':engine.run?.state==='cancelled'?'Analysis cancelled.':engine.id&&!finalizing?'Reading the material.':'Putting the evidence together.'}</h1><p>{engine.id&&!finalizing?'Your original images are being measured with the fixed model. Keep this page open or come back to this run later.':'Retrieving existing measurements and their evidence. The scientific results stay unchanged.'}</p><div role="status" aria-live="polite" className="active-stage">{!['failed','cancelled'].includes(engine.run?.state)&&<LoaderCircle className="spin" size={18}/>}<span>{engine.id&&!finalizing?(engine.run?.stage||'Preparing engine'):stage}{!finalizing&&engine.run?.elapsedSeconds!=null&&<small className="elapsed">Elapsed: {Math.floor(engine.run.elapsedSeconds/60)}m {Math.floor(engine.run.elapsedSeconds%60)}s</small>}</span></div>{engine.id&&!finalizing&&<ol className="processing-stages">{['Checking files','Measuring image structure','Comparing with known batches','Preparing review'].map((label,i)=><li key={label}><span>{i+1}</span>{label}</li>)}</ol>}{(error||engine.error)&&<p role="alert" className="error-banner">{error||engine.error}</p>}<div className="process-actions"><button className="secondary" onClick={()=>{requestId.current++;go('new');}}>Back to setup</button>{engine.busy&&<button className="text-button" onClick={()=>void engine.cancel()}>Cancel analysis</button>}</div></div></div>}
  {screen==='review'&&<><div className="page-heading compact"><div><h1>Your expertise adds context.</h1><p>Inspect the highlighted areas up close, then tell us what you see.</p></div><span className="badge">Human review · optional</span></div><div className="review-layout"><section className="review-images-column"><div className="review-toolbar"><select aria-label="Field to review" value={previewField} onChange={e=>{setPreviewField(Number(e.target.value));setRoi(null);setTag('');setNote('');}}>{data?.fields?.map((f:any,i:number)=><option key={f.id} value={i}>{f.id} · BSE</option>)}</select><span>{imageUrl&&!previewError?'Original source · magnified detail':'Saved segmentation artifact · Original TIFF unavailable'}</span></div>{field&&channel&&<ReviewImage runId={engine.id} field={field} channel={{...channel,available:!!(imageUrl&&!previewError)}} savedOverlayUrl={savedOverlayUrl} roi={roi} onSelect={next=>{setRoi(next);setTag('');}}/>}</section><aside className="review-form"><h2>What is in this region?</h2><p>Your interpretation becomes a note on the report. It does not change the model’s measurements.</p><div className="review-tags">{['Graphite','Silicon-containing region','Pore or gap','Image artefact','Not sure'].map(t=><button className={tag===t?'tag-button selected':'tag-button'} key={t} onClick={()=>setTag(t)}>{t}{tag===t&&<Check size={16}/>}</button>)}</div><label className="note-label">Add context <span className="muted">(optional)</span><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="What should the next reviewer know?" rows={3}/></label><p className="fineprint">Material names are stated by Polaron and not verified from the image. Silicon and silicon oxide cannot be distinguished here.</p>{error&&<p role="alert" className="error-text">{error}</p>}<button className="primary" disabled={!imageUrl||previewError} onClick={()=>saveReview(false)}>Save review and continue <ArrowRight size={17}/></button><button className="text-button skip-review" onClick={()=>saveReview(true)}>Continue without a region review <ArrowRight size={15}/></button></aside></div></>}
  {screen==='accuracy'&&<Suspense fallback={<div className="empty-state" role="status"><LoaderCircle size={24} className="spin"/><p>Opening saved model accuracy…</p></div>}><ModelAccuracy/></Suspense>}
  {screen==='results'&&(data?<Results data={{...data,metadata:data.metadata||metadata}} criteria={data.criteria||criteria} review={review} onNew={()=>go('new')}/>:<div className="empty-state"><LoaderCircle size={24} className="spin"/><p>{savedError||'Opening the saved evaluation…'}</p><button className="secondary" onClick={()=>go('new')}>Back to setup</button></div>)}
  </main><footer className="app-footer"><span>cottrell. <span className="muted">Evidence before conclusions.</span></span><span>Image-level screening · Cause not established</span></footer>
 </div>;
}
